/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class application_MainController */

#ifndef _Included_application_MainController
#define _Included_application_MainController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     application_MainController
 * Method:    berechneKautionsKosten
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_application_MainController_berechneKautionsKosten
  (JNIEnv *, jobject);

/*
 * Class:     application_MainController
 * Method:    holeAktuellenStromverbrauchInKWh
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_application_MainController_holeAktuellenStromverbrauchInKWh
  (JNIEnv *, jobject);

/*
 * Class:     application_MainController
 * Method:    holeAktuellenWasserverbrauchInKubikM
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_application_MainController_holeAktuellenWasserverbrauchInKubikM
  (JNIEnv *, jobject);

/*
 * Class:     application_MainController
 * Method:    berechneMieteinnahmenGesamtInEuro
 * Signature: ([DLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_application_MainController_berechneMieteinnahmenGesamtInEuro
  (JNIEnv *, jobject, jdoubleArray, jstring);

/*
 * Class:     application_MainController
 * Method:    erstelleMieterObjekt
 * Signature: (JLjava/lang/String;Ljava/lang/String;IIJ)Lmodel/Mieter;
 */
JNIEXPORT jobject JNICALL Java_application_MainController_erstelleMieterObjekt
  (JNIEnv *, jobject, jlong, jstring, jstring, jint, jint, jlong);

/*
 * Class:     application_MainController
 * Method:    erstelleMietobjektObjekt
 * Signature: (JIDILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_application_MainController_erstelleMietobjektObjekt
  (JNIEnv *, jobject, jlong, jint, jdouble, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
