/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test */

#ifndef _Included_test
#define _Included_test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BasisControl
 * Method:    berechneKautionsKosten
 * Signature: ()V
 */
JNIEXPORT float JNICALL Java_BasisControl_berechneKautionsKosten
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

