/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BasisControl */

#ifndef _Included_BasisControl
#define _Included_BasisControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BasisControl
 * Method:    berechneKautionsKosten
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_BasisControl_berechneKautionsKosten
  (JNIEnv *, jobject);

/*
 * Class:     BasisControl
 * Method:    holeStromzaehlerStandInKWh
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_BasisControl_holeStromzaehlerStandInKWh
  (JNIEnv *, jobject);

/*
 * Class:     BasisControl
 * Method:    holeWasserverbrauchInKubikM
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_BasisControl_holeWasserverbrauchInKubikM
  (JNIEnv *, jobject);

/*
 * Class:     BasisControl
 * Method:    berechneMieteinnahmenGesamtInEuro
 * Signature: ([ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_BasisControl_berechneMieteinnahmenGesamtInEuro
  (JNIEnv *, jobject, jintArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
